name: stripedart
description: Dart library for the Stripe API. The Stripe Dart library provides convenient access to the Stripe API from applications written in server-side Dart.
version: 1.1.2
homepage: https://github.com/IGLU-Agency/stripe-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1
  json_annotation: ^4.0.1

dev_dependencies:
  test: ^1.16.8
  json_serializable: ^4.1.0
  build_runner: ^1.12.2
